version: '3'

services:

  launchy-backend-dev:
    image: launchy-backend
    container_name: "launchy-backend"
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_URL: xxx
      GOOGLE_AUTH_CLIENT_ID: "abc"
      GOOGLE_AUTH_CLIENT_SECRET: "abc"
      JWT_ACCESS_TOKEN_EXPIRATION_TIME_SECONDS: 900 # 15 min
      JWT_REFRESH_TOKEN_EXPIRATION_TIME_SECONDS: 604800 # 1 week
      JWT_AUDIENCE: xxx
      JWK_PUB_AND_PRIV_KEYSET_BASE64: xxx
      CLIENT_APP_URL: "http://localhost:3000"
      AWS_ACCESS_KEY_ID: xxx
      AWS_SECRET_ACCESS_KEY: xxx
      AWS_KMS_KEY_ID: xxx
      NODE_ENV: "development"
      POSTGRES_HOST: xxx
      POSTGRES_PORT: 5432
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: "launchy"